name: TEST CI/CD

on:
  push:
  workflow_dispatch:
  pull_request:

concurrency:
  group: "test-ci-cd"
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests & Collect Coverage
        run: npm test -- --coverage

      - name: Run SonarCloud Analysis
        run: |
          npx sonarqube-scanner \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs:
      - sonarcloud
    name: semantic-release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Login to docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u filippogurioli --password-stdin
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
